##################################################
# AppVeyor
##################################################
# Modified from https://github.com/ruslo/polly/blob/master/appveyor.yml.

version: "0.0.1-b{build}-{branch}"

clone_depth: 50

branches:
  except:
    - gh-pages

image: Visual Studio 2017

environment:
  matrix:
    ####################
    # Others
    ####################
    # See .travis.yml.

    ####################
    # Windows
    ####################
    - TOOLCHAIN: "vs-15-2017"
      CONFIG: Release

    - TOOLCHAIN: "vs-15-2017"
      CONFIG: Debug

    - TOOLCHAIN: "vs-15-2017-win64"
      CONFIG: Release

    - TOOLCHAIN: "vs-15-2017-win64"
      CONFIG: Debug

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Clone submodules
  - cmd: git submodule update --init --recursive

  # Install dependencies (CMake, Ninja)
  - cmd: set POLLY_SOURCE_DIR=%cd%\polly
  - cmd: python %POLLY_SOURCE_DIR%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  - cmd: set MINGW_PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

  # MSYS2 location
  - cmd: set MSYS_PATH=C:\msys64\usr\bin

build_script:
  - cmd: python %POLLY_SOURCE_DIR%\bin\build.py --home . --toolchain %TOOLCHAIN% --config %CONFIG% --verbose --clear --install --test
