##################################################
# Travis CI
##################################################
# Modified from https://github.com/ruslo/polly/blob/master/.travis.yml.

language:
  - minimal

addons:
  apt:
    packages:
      - python3-pip

dist:
  - trusty

matrix:
  include:
    ####################
    # Android
    ####################
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-x86-clang-libcxx CONFIG=Release
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-x86-clang-libcxx CONFIG=Debug
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-armeabi-clang-libcxx CONFIG=Release
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-armeabi-clang-libcxx CONFIG=Debug
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-armeabi-v7a-clang-libcxx CONFIG=Release
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-armeabi-v7a-clang-libcxx CONFIG=Debug
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-mips-clang-libcxx CONFIG=Release
    - os: linux
      env: TOOLCHAIN=android-ndk-r15c-api-16-mips-clang-libcxx CONFIG=Debug

    ####################
    # iOS
    ####################
    - os: osx
      osx_image: xcode10.0
      env: TOOLCHAIN=ios-nocodesign-12-0-dep-9-0-bitcode-cxx11 CONFIG=Release
    - os: osx
      osx_image: xcode10.0
      env: TOOLCHAIN=ios-nocodesign-12-0-dep-9-0-bitcode-cxx11 CONFIG=Debug

    ####################
    # Linux
    ####################
    - os: linux
      env: TOOLCHAIN=libcxx CONFIG=Release
    - os: linux
      env: TOOLCHAIN=libcxx CONFIG=Debug

    ####################
    # macOS
    ####################
    - os: osx
      osx_image: xcode10.1
      env: TOOLCHAIN=osx-10-14 CONFIG=Release
    - os: osx
      osx_image: xcode10.1
      env: TOOLCHAIN=osx-10-14 CONFIG=Debug

    ####################
    # Windows
    ####################
    # See appveyor.yml.

install:
  # Info about OS
  - uname -a

  - export HOMEBREW_NO_AUTO_UPDATE=1

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi
  # fix broken clang link on Travis-CI
  - if [[ "`uname`" == "Linux" ]]; then mkdir clang-bin; ln -s /usr/local/clang-5.0.0/bin/clang++ clang-bin/clang++-5.0; fi
  - if [[ "`uname`" == "Darwin" ]]; then mkdir clang-bin; ln -s /usr/bin/clang++ clang-bin/clang++-5.0; fi

  # Install dependencies (CMake, Android NDK)
  - POLLY_SOURCE_DIR="`pwd`/polly"
  - python3 "${POLLY_SOURCE_DIR}/bin/install-ci-dependencies.py"

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:`pwd`/clang-bin:${PATH}"
  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"
  - export ANDROID_NDK_r15c="`pwd`/_ci/android-ndk-r15c"
  - export ANDROID_NDK_r17="`pwd`/_ci/android-ndk-r17"

script:
  - >
    python3 "${POLLY_SOURCE_DIR}/bin/build.py"
    --home .
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --clear
    --install
    --test

branches:
  except:
    - gh-pages
