##################################################
# Variables
##################################################

set (SECTION_HEADER "==================================================")
set (SECTION_SPLITTER "--------------------------------------------------")
set (SECTION_FOOTER "==================================================")

if (NOT DEFINED TOOLCHAIN_TAG)
  if (DEFINED CMAKE_TOOLCHAIN_FILE)
    set (TOOLCHAIN_TAG ${CMAKE_TOOLCHAIN_FILE})
  else ()
    message (FATAL_ERROR "CMAKE_TOOLCHAIN_FILE and TOOLCHAIN_TAG are not defined.")
  endif ()
endif ()

string (FIND ${TOOLCHAIN_TAG} "android" ANDROID)
if (${ANDROID} EQUAL "-1")
  set (ANDROID FALSE)
else ()
  set (ANDROID TRUE)
endif ()
string (FIND ${TOOLCHAIN_TAG} "ios" IOS)
if (${IOS} EQUAL "-1")
  set (IOS FALSE)
else ()
  set (IOS TRUE)
endif ()
string (FIND ${TOOLCHAIN_TAG} "libcxx" LINUX)
if (${LINUX} EQUAL "-1")
  set (LINUX FALSE)
else ()
  set (LINUX TRUE)
endif ()
string (FIND ${TOOLCHAIN_TAG} "osx" MACOS)
if (${MACOS} EQUAL "-1")
  set (MACOS FALSE)
else ()
  set (MACOS TRUE)
endif ()
string (FIND ${TOOLCHAIN_TAG} "vs" WINDOWS)
if (${WINDOWS} EQUAL "-1")
  set (WINDOWS FALSE)
else ()
  set (WINDOWS TRUE)
endif ()

if (ANDROID)
  set (PLATFORM "ANDROID")
elseif (IOS)
  set (PLATFORM "IOS")
elseif (LINUX)
  set (PLATFORM "LINUX")
elseif (MACOS)
  set (PLATFORM "MACOS")
else (WINDOWS)
  set (PLATFORM "WINDOWS")
endif ()

if (NOT DEFINED ENV{CI})
  set (ENV{CI} FALSE)
elseif ($ENV{CI} EQUAL "true" # Travis CI, AppVeyor
        OR $ENV{CI} EQUAL "True") # AppVeyor
  set (ENV{CI} TRUE)
endif ()

message (STATUS ${SECTION_HEADER})
message (STATUS "Variables")
message (STATUS ${SECTION_SPLITTER})
message (STATUS "Name: ${PROJECT_NAME}")
message (STATUS "Version: ${PROJECT_VERSION}")
message (STATUS "Toolchain: ${TOOLCHAIN_TAG}")
message (STATUS "Platform: ${PLATFORM}")
message (STATUS "Continuous Integration: $ENV{CI}")
message (STATUS ${SECTION_FOOTER})
